<a href="https://colab.research.google.com/github/albertofernandezvillan/computer-vision-and-deep-learning-course/blob/main/forward.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MLP forward

In [ ]:
import torch

In [ ]:
n_input = 3
n_hidden = 7
n_output = 1

In [ ]:
def act(x):
    return 1/(1+torch.exp(-x))

In [ ]:
W1 = torch.randn(n_input, n_hidden)
W2 = torch.randn(n_hidden, n_output)
B1 = torch.randn(1, n_hidden)
B2 = torch.randn(1, n_output)

In [ ]:
input = torch.rand(1, n_input)

In [ ]:
output = act(act(input @ W1 + B1) @ W2 + B2)
output

tensor([[0.8896]])

## Steps

In [ ]:
input @ W1

tensor([[-0.7807,  1.0567,  0.3053,  0.3670,  0.2926,  0.7168, -0.6421]])

In [ ]:
input @ W1 + B1

tensor([[-0.7045, -0.9776, -0.8295,  0.8542, -0.1621,  0.4958, -0.5418]])

In [ ]:
act(input @ W1 + B1)

tensor([[0.3308, 0.2734, 0.3038, 0.7014, 0.4596, 0.6215, 0.3678]])

In [ ]:
output_layer1 = act(input @ W1 + B1)

In [ ]:
output_layer2 = act(output_layer1 @ W2 + B2)