<a href="https://colab.research.google.com/github/albertofernandezvillan/computer-vision-and-deep-learning-course/blob/main/numpy_introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" style="padding-right:10px;" src ="https://raw.githubusercontent.com/albertofernandezvillan/computer-vision-and-deep-learning-course/main/assets/university_oviedo_logo.png" width=300 px>

This notebook is from the Course "***Computer vision in the new era of Artificial Intelligence and Deep Learning***", or "*Visión por computador en la nueva era de la Inteligencia Artificial y el Deep Learning*" (ES) from the "Second quarter university extension courses" that the University of Oviedo is offering (05/04/2021 - 16/04/2021)

<[Github Repository](https://github.com/albertofernandezvillan/computer-vision-and-deep-learning-course) | [Course Web Page Information](https://www.uniovi.es/estudios/extension/cursos2c/-/asset_publisher/SEp0PJi4ISGo/content/vision-por-computador-en-la-nueva-era-de-la-inteligencia-artificial-y-el-deep-learning?redirect=%2Festudios%2Fextension%2Fcursos2c)>

# Summary
<center><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/320px-NumPy_logo_2020.svg.png"></center>

NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. In this notebook, we will learn the basics of numerical analysis using the NumPy library.

# Introduction

The core functionality of NumPy is its "ndarray", for n-dimensional array, data structure. In contrast to Python's built-in list data structure, these arrays are homogeneously typed: all elements of a single array must be of the same type. To use Numpy, we first need to import the `numpy` package. At the time of writing this notebook (April 2021), Numpy version is: `1.19.5`.

In [1]:
import numpy as np

print("Numpy version: {}".format(np.__version__))

Numpy version: 1.19.5


# The basics

NumPy’s main object is the homogeneous multidimensional array. NumPy’s array class is called `ndarray`. It is also known by the alias `array`. Note that `numpy.array` is not the same as the Standard Python Library class `array.array`, which only handles one-dimensional arrays and offers less functionality.

`numpy.array()` is just a method which returns an array object of the type `ndarray`.


In [5]:
import array as arr
import numpy as np

my_python_array = arr.array("i", [1,2,3,4,5,6])
my_numpy_array = np.array([1,2,3,4,5,6])

print("my_python_array: {} with type: {}".format(my_python_array, type(my_python_array)))
print("my_numpy_array: {} with type: {}".format(my_numpy_array, type(my_numpy_array)))

my_python_array: array('i', [1, 2, 3, 4, 5, 6]) with type: <class 'array.array'>
my_numpy_array: [1 2 3 4 5 6] with type: <class 'numpy.ndarray'>


The more important **attributes** of an `ndarray` object are:

- `a.shape`: tuple of integers indicating the size of the array in each dimensions
- `a.ndim`: the number of axes (dimensions) of the array (also called as rank)
- `a.size`: the total number of elements of the array
- `a.dtype`: an object describing the type of the elements in the array
- `a.data`: the buffer containing the actual elements of the array

In [6]:
import numpy as np

# Creating a numpy array:
my_numpy_array = np.array([[1,2,3],[4,5,6]])

# Show its attributes:
print(my_numpy_array)
print(my_numpy_array.shape)
print(my_numpy_array.ndim)
print(my_numpy_array.size)
print(my_numpy_array.dtype)
print(my_numpy_array.data)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64


# Array creation

There are many ways to create Numpy arrays. For example, you can create an array from a regular Python list or tuple using the `array()` function.  The type of the resulting array is deduced from the type of the elements in the sequences, but it can be specified via the key word argument `dtype`.

In [7]:
import numpy as np

# Creating a numpy array from a Python list:
my_numpy_array = np.array([1,2,3,4,5,6])

print(my_numpy_array.dtype)
print(my_numpy_array)

int64
[1 2 3 4 5 6]


In [8]:
import numpy as np

# Creating a numpy array from a Python with an explicit type:
my_numpy_array = np.array([1,2,3,4,5,6], dtype=np.float32)

print(my_numpy_array.dtype)
print(my_numpy_array)

float32
[1. 2. 3. 4. 5. 6.]


Do you remember that Numpy arrays are homogeneously typed: all elements of a single array must be of the same type? Let's check it if we can create a Numpy array with diffent types.

In [9]:
import numpy as np

# Creating a Numpy array from a Pytho list:
my_numbers = np.array(["123", 3, 6, 9, 12])

print(my_numbers)
print(my_numbers.dtype) # 3-character string

['123' '3' '6' '9' '12']
<U3


In [10]:
import numpy as np

# Creating a Numpy array from a Pytho list with an explicit type
my_numbers = np.array(["123", 3, 6, 9, 12], dtype=np.int16)

print(my_numbers)
print(my_numbers.dtype) # int16

[123   3   6   9  12]
int16


In connection with array creation, Numpy provides several functions:
- `np.array([1, 2, 3])`: This creates an array from a list of values
- `np.zeros((3,4))`: This creates an array of zeros with the specified shape
- `np.ones((3,4))`: This creates an array of ones with the specified shape
- `np.eye(2)`: This creates a diagonal `2x2` array
- `np.random.random((2,2))`: This creates a random array with the specified shape
- `np.linspace(0,10,21)`: This creates an array with `21` elements from `0` to `10`
- `np.arange(0,10.5,0.5)`: This cretes an array from `0` to `10` (the upper interval `10.5` is not included) with a step of `0.5`



In [11]:
# Creating some numpy arrays:
print(np.array([1, 2, 3]))
print(np.zeros((3,4), dtype=np.int16)) # 3 rows, 4 cols and type np.int16
print(np.ones((3,4)))                  # 3 rows, 4 cols
print(np.eye(2))

# Set seed for reproducibility
np.random.seed(seed=1234)
print(np.random.random((2,2)))

# These two lines creates the same array:
print(np.linspace(0, 10, 21))
print(np.arange(0, 10.5, 0.5))

print(np.linspace(0, 10, 21).shape)
print(np.arange(0, 10.5, 0.5).shape)

# Let's check it:
print(np.array_equal(np.linspace(0,10,21), np.arange(0,10.5,0.5)))

[1 2 3]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0.]
 [0. 1.]]
[[0.19151945 0.62210877]
 [0.43772774 0.78535858]]
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]
(21,)
(21,)
True


# Arithmetic operations with arrays

We can perform arithmetic operations with arrays (e.g. subtraction, addition, division, multiplication, ...). See next code cell for some practical examples.






In [14]:
array_a = np.arange(1, 10, 1)
array_b = np.arange(1, 10, 1)

print(array_a)
print(array_b)

print(array_a + array_b)

print(array_b - array_a)
print(np.subtract(array_b, array_a))

print(array_a / array_b)
print(np.divide(array_a, array_b))

# Here, we’re adding an array and a value (scalar). 
# Their dimensions aren’t compatible 
# This is where broadcasting comes in. The scalar is broadcast across the array 
#so that they have compatible shapes.
print(array_a + 5)

# Broadcasting also happens here:
print(array_a * 5)

# See that array multiplication is not matrix multiplication
# If you multiply two NumPy arrays together, NumPy assumes you want to do 
# element-wise multiplication.
print(array_a * array_b)
print(np.multiply(array_a, array_b))

# As the name suggests, this computes the dot product of two vectors.
print(array_a.dot(array_b))

# If you use this function with a pair of 2D vectors, it does matrix multiplication. 
# But it is recommended to use np.matmul() for this purpose
# See here 'https://blog.finxter.com/numpy-matmul-operator/' for more information
print("\nPerforming matrix multiplication...\n")
my_matrix_1 = np.ones((3, 2))
my_matrix_2 = np.ones((2, 4))
print(my_matrix_1)
print(my_matrix_2)

# Multiplying a matrix of shape (3,2) with another of (2,4) give us a new one with shape (3,4)
print(np.matmul(my_matrix_1, my_matrix_2))
print(np.matmul(my_matrix_1, my_matrix_2).shape)

# We cannot perform matrix multiplication with shapes (2,4) amd (3,2):
try:
  print(np.matmul(my_matrix_2, my_matrix_1))
except ValueError:
  print("Error tryring to perform matmul: size 3 is different from 4")

# dot product is not recommended for matrix multiplication:
print(my_matrix_1.dot(my_matrix_2))

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14 16 18]
[0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 6  7  8  9 10 11 12 13 14]
[ 5 10 15 20 25 30 35 40 45]
[ 1  4  9 16 25 36 49 64 81]
[ 1  4  9 16 25 36 49 64 81]
285

Performing matrix multiplication...

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
(3, 4)
Error tryring to perform matmul: size 3 is different from 4
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


# Indexing and slicing

We can access elements of an array by using their indices. This is called **indexing**. 

- For one-dimensional Numpy arrays, you only need to specify one index value, which is the position of the element in the Numpy array (e.g. `arrayname[index]`).

- For two-dimensional Numpy arrays, you need to specify both a row index and a column index for the element (e.g. `arrayname[indexrow,indexcol]`).

First of all, let's create a one-dimensional Numpy array and see how indexing works.

In [15]:
import numpy as np

# Create the array from a Python list:
my_array = np.array([10,20,30,40,50])

print("Created array: {} with a shape of {}".format(my_array, my_array.shape))
print("First element of the array: {}".format(my_array[0]))
print("Last element of the array: {}".format(my_array[my_array.shape[0] - 1]))

Created array: [10 20 30 40 50] with a shape of (5,)
First element of the array: 10
Last element of the array: 50


Now, let's create a two-dimensional Numpy array with shape `(3,5)`, which means that this array has `3` rows and `5` cols. To access an specific element of the array you have to provide first the row index and then, the column index. You can use this image as a reference.

<img src="https://raw.githubusercontent.com/albertofernandezvillan/computer-vision-and-deep-learning-course/main/assets/numpy_and_pandas_axes_with_values.jpg" width=600>

In [16]:
import numpy as np

# Create the array from Python lists:
my_array = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

print(my_array)
print(my_array.shape)

row = 1
col = 2
print(my_array[row, col])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
(3, 5)
8


At this point, let's see how to perform **slicing**. Slicing in Python means taking elements from one given index to another given index:

- We pass slice instead of index like this: `[start:end]`
- We can also define the step, like this: `[start:end:step]`
- If we don't pass start its considered `0`
- If we don't pass end its considered length of array in that dimension
- If we don't pass step its considered `1`

In [17]:
import numpy as np

# Create the array from a Python list:
my_array = np.array([10,20,30,40,50,60,70,80])

print(my_array)
print(my_array[0:7])
print(my_array[0:7:2])

[10 20 30 40 50 60 70 80]
[10 20 30 40 50 60 70]
[10 30 50 70]


In [18]:
import numpy as np

# Create the array from Python lists:
my_array = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

print(my_array)
print(my_array[0:2, 1:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[2 3]
 [7 8]]


We can use the minus operator to refer to an index from the end (this is called negative slicing).

In [19]:
import numpy as np

# Create the array from a Python list:
my_array = np.array([10,20,30,40,50,60,70,80])

print(my_array)
print(my_array[-6:-1])
print(my_array[-6:-1:2])
print(my_array[-6:])
print(my_array[:-1:2])

[10 20 30 40 50 60 70 80]
[30 40 50 60 70]
[30 50 70]
[30 40 50 60 70 80]
[10 30 50 70]


A slice of an array is a view into the same data, so modifying it will modify the original array.

In [20]:
import numpy as np

# Create the array from a Python list:
my_array = np.array([10,20,30,40,50,60,70,80])

my_array[0:7:2] = 500
print(my_array)

[500  20 500  40 500  60 500  80]


# Axis operations

We can also do operations across a specific axis. For this, the previously included figure can also be useful. Axes are like directions along the NumPy array. In a 2-dimensional array:
- `axis 0` is the axis that points down the rows 
- `axis 1` is the axis that points horizontally across the columns.

Let's see how this works with both `np.sum()` and `np.max()` functions.

In [21]:
import numpy as np

# Create the array from Python lists:
my_array = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

print(my_array)
print(np.sum(my_array))
print(np.sum(my_array, axis=0))
print(np.sum(my_array, axis=1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
120
[18 21 24 27 30]
[15 40 65]


In [22]:
import numpy as np

# Create the array from Python lists:
my_array = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

print(np.max(my_array))
print(np.max(my_array, axis=0))
print(np.max(my_array, axis=1))

15
[11 12 13 14 15]
[ 5 10 15]


# Exercises

<img  align="left" style="padding-right:10px;" src="https://raw.githubusercontent.com/albertofernandezvillan/computer-vision-and-deep-learning-course/main/assets/pencil.jpg" width=50> Numpy slicing and indexing are ver important. Therefore, we have included an exercise related to these topics. The task here is to reproduce the obtained results using the following image as reference.

<img src="https://raw.githubusercontent.com/albertofernandezvillan/dl-ml-notebooks/main/assets/numpy-indexing.jpg">


In [23]:
# Ref here for more information: https://www.geeksforgeeks.org/numpy-indexing/
# Import required packages:
import numpy as np

# Create a (6x6) array:
a = np.array([[0, 1, 2, 3, 4, 5], 
              [6, 7, 8, 9, 10, 11], 
              [12, 13, 14, 15, 16, 17], 
              [18, 19, 20, 21, 22, 23], 
              [24, 25, 26, 27, 28, 29], 
              [30, 31, 32, 33, 34, 35]])

# slicing and indexing
result_1 = a[0, 3:5]
result_2 = a[4:, 4:]
result_3 = a[:, 2]
result_4 = a[2::2, ::2]

print(result_1)
print(result_2)
print(result_3)
print(result_4)

[3 4]
[[28 29]
 [34 35]]
[ 2  8 14 20 26 32]
[[12 14 16]
 [24 26 28]]


One last note is in connection with `result_1 = a[0, 3:5]`. See the obtained shape (of lower rank than `a`). This is because we are mixing both indexing and slicing. We can use `result_1 = a[0:1, 3:5]` to obtain the same rank.

In [24]:
# Ref here for more information: https://www.geeksforgeeks.org/numpy-indexing/
# Import required packages:
import numpy as np

# Create a (6x6) array:
a = np.array([[0, 1, 2, 3, 4, 5], 
              [6, 7, 8, 9, 10, 11], 
              [12, 13, 14, 15, 16, 17], 
              [18, 19, 20, 21, 22, 23], 
              [24, 25, 26, 27, 28, 29], 
              [30, 31, 32, 33, 34, 35]])
print(a.shape)

print(a[0, 3:5])
print(a[0, 3:5].shape)

print(a[0:1, 3:5])
print(a[0:1, 3:5].shape)

(6, 6)
[3 4]
(2,)
[[3 4]]
(1, 2)


# Conclusions

In this notebook, an introduction to Numpy was given. If you are new to Numpy, it is recommended to see these official tutorials:

- [NumPy: the absolute basics for beginners](https://numpy.org/doc/stable/user/absolute_beginners.html)
- [NumPy quickstart](https://numpy.org/doc/stable/user/quickstart.html)
- [NumPy basics](https://numpy.org/doc/stable/user/basics.html)




