<a href="https://colab.research.google.com/github/albertofernandezvillan/computer-vision-and-deep-learning-course/blob/main/pandas_introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" style="padding-right:10px;" src ="https://raw.githubusercontent.com/albertofernandezvillan/computer-vision-and-deep-learning-course/main/assets/university_oviedo_logo.png" width=300 px>

This notebook is from the Course "***Computer vision in the new era of Artificial Intelligence and Deep Learning***", or "*Visión por computador en la nueva era de la Inteligencia Artificial y el Deep Learning*" (ES) from the "Second quarter university extension courses" that the University of Oviedo is offering (05/04/2021 - 16/04/2021)

<[Github Repository](https://github.com/albertofernandezvillan/computer-vision-and-deep-learning-course) | [Course Web Page Information](https://www.uniovi.es/estudios/extension/cursos2c/-/asset_publisher/SEp0PJi4ISGo/content/vision-por-computador-en-la-nueva-era-de-la-inteligencia-artificial-y-el-deep-learning?redirect=%2Festudios%2Fextension%2Fcursos2c)>

## Summary

In this notebook, a quick introduction to pandas is given. More specifically, we are going to cover:

- Introduction to pandas
- Pandas data table representation
- Axis in Series and axes in DataFrames
- Creating pandas DataFrames
- DataFrame attributes
- DataFrame methods

# Introduction to pandas

Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool, built on top of the Python programming language. In particular, it offers data structures and operations for manipulating numerical tables and time series.

<center><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Pandas_mark.svg/128px-Pandas_mark.svg.png"></center>

To load the pandas package and start working with it, import the package:

```python
import pandas as pd
```

The community agreed alias for pandas is `pd`, so loading pandas as `pd` is assumed standard practice for all of the pandas documentation.

At the time of writing these tutorials installed version of pandas in Colab is `1.1.5` (release date: December 07, 2020), and latest version of pandas is `1.2.3` (release date: Mar 02, 2021). 

```python
import pandas as pd

print("pandas version: '{}'".format(pd.__version__))
```

`pandas version: '1.1.5'`


# Pandas data table representation

As commented in the introduction, pandas offers data structures that make data manipulation and analysis easy (among other thins). The [DataFrame](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html) is one of these structures. The [Series](https://pandas.pydata.org/docs/reference/api/pandas.Series.html) is another useful structure, but let's start with the DataFrame.

In pandas, a data table is called a **DataFrame**. The short explanation about what is a DataFrame could be "*a two-dimensional, size-mutable, potentially heterogeneous tabular data*". It is generally the most commonly used pandas object.

<center><img src="https://raw.githubusercontent.com/albertofernandezvillan/computer-vision-and-deep-learning-course/main/assets/pandas_dataframe.png" width=400></center>






Next Figure ([extracted from one of the best tutorials you will find about pandas](https://medium.com/dunder-data/selecting-subsets-of-data-in-pandas-6fcd0170be9c)), shows the anatomy of a DataFrame.

<center><img src="https://raw.githubusercontent.com/albertofernandezvillan/computer-vision-and-deep-learning-course/main/assets/dataframe_example.png" width=900></center>

A DataFrame is composed of three different components, the **index**, **columns**, and the **data**. The data is also known as the **values**.

- The index in previous example are just the integers beginning from `0` up to `n-1`, where `n` is the number of rows in the table. Each individual value of the index is called a label.

- The columns are the sequence of values at the very top of the DataFrame. Each individual value of the columns is called a column.

- Everything else not in bold font is the data or values. As you can see, there are also missing values (represented as NaN).


It is also common terminology to refer to the rows or columns as an axis. See next point for a quick introduction about axes.

A pandas **Series** is a one-dimensional data structure that comprises of a key-value pair. It can be seen as a Python dictionary, except it provides more freedom to manipulate and edit the data.




# Axis in Series and axes in DataFrames

While DataFrames are two-dimensional structures, a Series is a one-dimensional structure. We will understand how axis works in Series and how axes work in DataFrames.

Let's start with Series. As commented briefly above, series is a one-dimensional array of values. Under the hood, it uses NumPy `ndarray`. That is where the term "axis" came from. Series object has only "`axis 0`" because it has only one dimension. 

Just as a note, usually, in Python, one-dimensional structures are displayed as a row of values. On the contrary, Series is displayed as a column of values. Let's compare a Series with a NumPy array in the following example.


In [1]:
import pandas as pd
import numpy as np

serie = pd.Series(['a','b','c'])
print("serie shape: {}".format(serie.shape))
print(serie)
print("second value of the serie (serie[1]): {}".format(serie[1]))

np_array = np.array(['a','b','c'])
print("array shape: {}".format(np_array.shape))
print(np_array)
print("second value of the array (np_array[1]): {}".format(np_array[1]))


serie shape: (3,)
0    a
1    b
2    c
dtype: object
second value of the serie (serie[1]): b
array shape: (3,)
['a' 'b' 'c']
second value of the array (np_array[1]): b


As DataFrame is a two-dimensional data structure, it has columns and rows. DataFrame has two axes: "`axis 0`" and "`axis 1`":
- "`axis 0`" represents rows 
- "`axis 1`" represents columns

Moreover, in the example above we used the `[]` operator to access both a value the Series and a value in the one dimensional array. 

To access an element within DataFrame we need to provide two indexes (one per each axis). Also, instead of `[]` operator, we need to use `.loc` or `.iloc` indexers. We will see how to use the `[]` operator and `.loc` or `.iloc` indexers later in this notebook.

The takeaway so far is that:
- Series object has only "`axis 0`" and we can access individual values using` []` operator
- DataFrame object has `axis 0` (rows) and `axis 1` (cols) and individual values are accessed using `.loc` or `iloc` indexers.


# Creating pandas DataFrame

Pandas DataFrame can be created in [multiple ways](https://www.geeksforgeeks.org/different-ways-to-create-pandas-dataframe/). 

1. For example, we can call `pd.DataFrame(data=None, index=None, columns=None)` with `data` set to a NumPy array, `index` set to a list of row names, and `column` set to a list of column names to create a Pandas DataFrame.

In [2]:
import pandas as pd
import numpy as np

numpy_data = np.array([np.arange(3), np.arange(3,6), np.arange(6,9), np.arange(9,12)], dtype = "uint8")
print("This is the numpy array with the data: \n {}".format(numpy_data))

df = pd.DataFrame(data=numpy_data, 
                  index=["index1", "index2", "index3", "index4"],
                  columns=["column1", "column2", "column3"])

print("This is the created Dataframe: \n {}".format(df))

# Notice that the inferred dtype is uint8.
print("Inferred dtype \n{}".format(df.dtypes))

This is the numpy array with the data: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
This is the created Dataframe: 
         column1  column2  column3
index1        0        1        2
index2        3        4        5
index3        6        7        8
index4        9       10       11
Inferred dtype 
column1    uint8
column2    uint8
column3    uint8
dtype: object


2. We can also create the DataFrame from a json structure. Note here that as pandas can export the data in multiple ways (included json) using `to_*` method, we can see how the json structure looks like. In this case, we are going to use `to_json()`:

```python
print(df.to_json())
```
The output is:

```
{"column1":{"index1":0,"index2":3,"index3":6,"index4":9},"column2":{"index1":1,"index2":4,"index3":7,"index4":10},"column3":{"index1":2,"index2":5,"index3":8,"index4":11}}
```

Therefore, we can create the same DataFrame as follows. Note that is not necessary to set both the `index` and `columns` because they are contained in the json structure:


In [3]:
data = {"column1":{"index1":0,"index2":3,"index3":6,"index4":9},
        "column2":{"index1":1,"index2":4,"index3":7,"index4":10},
        "column3":{"index1":2,"index2":5,"index3":8,"index4":11}}

df_2 = pd.DataFrame(data=data)

print(df_2)

# Notice that the inferred dtype is int64.
print("Inferred dtype \n{}".format(df_2.dtypes))

        column1  column2  column3
index1        0        1        2
index2        3        4        5
index3        6        7        8
index4        9       10       11
Inferred dtype 
column1    int64
column2    int64
column3    int64
dtype: object


3. We can also create the same DataFrame as follows. Note here that we have to include index set to a list of row names.

In [4]:
data = {"column1":[0,3,6,9],
        "column2":[1,4,7,10],
        "column3":[2,5,8,11]}

df_3 = pd.DataFrame(data=data, index=["index1", "index2", "index3", "index4"])
print(df_3)

# Notice that the inferred dtype is int64.
print("Inferred dtype \n{}".format(df_3.dtypes))

        column1  column2  column3
index1        0        1        2
index2        3        4        5
index3        6        7        8
index4        9       10       11
Inferred dtype 
column1    int64
column2    int64
column3    int64
dtype: object


4. Moreover, we can also create a DataFrame using lists of lists as `data`. Here, we have to include both the `index` and `columns`.

In [5]:
data = [[0,1,2],
        [3,4,5],
        [6,7,8],
        [9,10,11]]

df_4 = pd.DataFrame(data=data, 
                  index=["index1", "index2", "index3", "index4"],
                  columns=["column1", "column2", "column3"])
print(df_4)

# Notice that the inferred dtype is int64.
print("Inferred dtype \n{}".format(df_4.dtypes))

        column1  column2  column3
index1        0        1        2
index2        3        4        5
index3        6        7        8
index4        9       10       11
Inferred dtype 
column1    int64
column2    int64
column3    int64
dtype: object


Notice also that if we only set the parameter `data` and left the both `index` and `columns` parameters as default (`index=None`, `columns=None`):

*   rows labels are just integers beginning from `0` up to `n-1`, where `n` is the number of rows in the table
*   columns labels are just integers beginning from `0` up to `m-1`, where `m` is the number of columns in the table


In [6]:
data = [[0,1,2],
        [3,4,5],
        [6,7,8],
        [9,10,11]]

df_5 = pd.DataFrame(data=data)
print(df_5)

# Notice that the inferred dtype is int64.
print("Inferred dtype \n{}".format(df_5.dtypes))

   0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11
Inferred dtype 
0    int64
1    int64
2    int64
dtype: object


To enforce a single `dtype` (single type for all the values):

In [7]:
df_uint8 = pd.DataFrame(data=data, 
                  index=["index1", "index2", "index3", "index4"],
                  columns=["column1", "column2", "column3"],
                  dtype=np.uint8)

print(df_uint8)
print("dtype \n{}".format(df_uint8.dtypes))

        column1  column2  column3
index1        0        1        2
index2        3        4        5
index3        6        7        8
index4        9       10       11
dtype 
column1    uint8
column2    uint8
column3    uint8
dtype: object


# DataFrame attributes

DataFrame provides many attributes. For example and shown above, `dtype` is an example of attribute provided by DataFrame. Other attributes are shown below.

In [8]:
numpy_data = np.array([np.arange(3), np.arange(3,6), np.arange(6,9), np.arange(9,12)])                 

df = pd.DataFrame(data=numpy_data, 
                  index=["index1", "index2", "index3", "index4"],
                  columns=["column1", "column2", "column3"])

print(df)

# dtypes: Return the dtypes in the DataFrame.
print("\ndtypes \n{}\n".format(df.dtypes))

# shape: Return a tuple representing the dimensionality of the DataFrame.
print("shape: {}\n".format(df.shape))

# empty: Indicator whether DataFrame is empty.
print("empty: {}\n".format(df.empty))

# ndim: Return an int representing the number of axes / array dimensions.
print("ndim: {}\n".format(df.ndim))

# size: Return an int representing the number of elements in this object.
print("size: {}\n".format(df.size))

# values: Return a NumPy representation of the DataFrame.
print("values: \n{}\n".format(df.values))

# attrs: Dictionary of global attributes of this dataset.
# attrs is experimental and may change without warning.
print("attrs: \n{}".format(df.attrs))
print("df.attrs['mydata'] = 'myvalue'")
df.attrs['mydata'] = 'myvalue'
print("attrs: \n{}\n".format(df.attrs))

# columns: The column labels of the DataFrame.
print("columns: \n{}\n".format(df.columns))
print("columns.values: \n{}\n".format(df.columns.values))

# loc: Access a group of rows and columns by label(s) or a boolean array.
# .loc[] is primarily label based, but may also be used with a boolean array.
# Single label. Note this returns the row as a Series (e.g. df.loc['index1'])
# List of labels. Note using [[]] returns a DataFrame (e.g. df.loc[['index1','index2']]):
print("df.loc['index1']: \n{}\n".format(df.loc['index1']))
print("type(df.loc['index1']): {}\n".format(type(df.loc['index1'])))
print("df.loc[['index1','index2']]: \n{}\n".format(df.loc[['index1','index2']]))

# iloc: Purely integer-location based indexing for selection by position.
print("df.iloc[0]: \n{}\n".format(df.iloc[0]))
print("type(df.iloc[0]): {}\n".format(type(df.iloc[0])))
print("df.iloc[[0]]: \n{}\n".format(df.iloc[[0]]))
print("df.iloc[[0, 1]]: \n{}\n".format(df.iloc[[0, 1]]))

        column1  column2  column3
index1        0        1        2
index2        3        4        5
index3        6        7        8
index4        9       10       11

dtypes 
column1    int64
column2    int64
column3    int64
dtype: object

shape: (4, 3)

empty: False

ndim: 2

size: 12

values: 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

attrs: 
{}
df.attrs['mydata'] = 'myvalue'
attrs: 
{'mydata': 'myvalue'}

columns: 
Index(['column1', 'column2', 'column3'], dtype='object')

columns.values: 
['column1' 'column2' 'column3']

df.loc['index1']: 
column1    0
column2    1
column3    2
Name: index1, dtype: int64

type(df.loc['index1']): <class 'pandas.core.series.Series'>

df.loc[['index1','index2']]: 
        column1  column2  column3
index1        0        1        2
index2        3        4        5

df.iloc[0]: 
column1    0
column2    1
column3    2
Name: index1, dtype: int64

type(df.iloc[0]): <class 'pandas.core.series.Series'>

df.iloc[[0]]: 
        column1  column2  c

# DataFrame methods

Some of the methods are shown as follows. But first, let's create a sample DataFrame.

In [9]:
import numpy as np
import pandas as pd

numpy_data = np.array([np.arange(3), np.arange(3,6), np.arange(6,9), np.arange(9,12)])                 

df = pd.DataFrame(data=numpy_data, 
                  index=["index1", "index2", "index3", "index4"],
                  columns=["column1", "column2", "column3"])

**Viewing your data**: The first thing we can do when exploring a DataFrame is to print the first `n` rows (`.head(n=5)`) or to print the last `n` rows (`.tail(n=5)`), where `n` (optional) is the number of rows to show. Therefore:

*   [`DataFrame.head(n=5)`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.head.html): Return the first `n` rows.  It is useful for quickly testing that your data is loaded correctly.

*   [`DataFrame.tail(n=5)`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.tail.html#pandas.DataFrame.tail): Return the last `n` rows. It is useful for quickly verifying data, for example, after sorting or appending rows.


In [20]:
print(df.head(1))
print(df.tail(2))

        column1  column2  column3
index1        0        1        2
        column1  column2  column3
index3        6        7        8
index4        9       10       11


**Getting information about the data**: This can be done using:

*    `.info()`: provides a concise summary of your DataFrame. 
*   `.describe()`: returns a statistical summary
*   `.describe(include='all')`: gives full summary statistics

In [10]:
# .info() provides the key details about your dataset:
# (e.g. the number of rows and columns, the number of non-null values,
# what type of data is in each column, how much memory your DataFrame is using)

print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, index1 to index4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   column1  4 non-null      int64
 1   column2  4 non-null      int64
 2   column3  4 non-null      int64
dtypes: int64(3)
memory usage: 128.0+ bytes
None


In [11]:
print(df.describe())

        column1    column2    column3
count  4.000000   4.000000   4.000000
mean   4.500000   5.500000   6.500000
std    3.872983   3.872983   3.872983
min    0.000000   1.000000   2.000000
25%    2.250000   3.250000   4.250000
50%    4.500000   5.500000   6.500000
75%    6.750000   7.750000   8.750000
max    9.000000  10.000000  11.000000


In [23]:
print(df.describe(include='all'))

        column1    column2    column3
count  4.000000   4.000000   4.000000
mean   4.500000   5.500000   6.500000
std    3.872983   3.872983   3.872983
min    0.000000   1.000000   2.000000
25%    2.250000   3.250000   4.250000
50%    4.500000   5.500000   6.500000
75%    6.750000   7.750000   8.750000
max    9.000000  10.000000  11.000000


In [29]:
df = pd.DataFrame({'col_1':['a', 'b', 'c', 'd', 'a'], 'col_2': np.arange(5)})
df

col_1  col_2
0     a      0
1     b      1
2     c      2
3     d      3
4     a      4

In [30]:
# The default behavior is to only provide 
# a summary for the numerical columns.
df.describe()

col_2
count  5.000000
mean   2.000000
std    1.581139
min    0.000000
25%    1.000000
50%    2.000000
75%    3.000000
max    4.000000

In [32]:
df.describe(include='all')

col_1     col_2
count      5  5.000000
unique     4       NaN
top        a       NaN
freq       2       NaN
mean     NaN  2.000000
std      NaN  1.581139
min      NaN  0.000000
25%      NaN  1.000000
50%      NaN  2.000000
75%      NaN  3.000000
max      NaN  4.000000

**Append rows**: `append(other[, ignore_index, …])`: Append rows of other to the end of caller, returning a new object. This means that using `append()` will return a copy without affecting the original DataFrame.

In [12]:
# append(other[, ignore_index, …]): Append rows of other to the end of caller, returning a new object.
df_2 = df.loc[['index1','index2']]
df_result = df.append(df_2)
print(df_result)

# With ignore_index set to True:
df_result = df.append(df_2, ignore_index=True)
print(df_result)

        column1  column2  column3
index1        0        1        2
index2        3        4        5
index3        6        7        8
index4        9       10       11
index1        0        1        2
index2        3        4        5
   column1  column2  column3
0        0        1        2
1        3        4        5
2        6        7        8
3        9       10       11
4        0        1        2
5        3        4        5


**Insert column**: `insert(loc, column, value[, allow_duplicates])`: Insert column into DataFrame at specified location.

In [13]:
new_col = df['column1'] * 10
print(new_col)
df.insert(1, 'new_column', new_col)
print(df)

try:
  df.insert(1, 'new_column', new_col)
except ValueError:
  print("\n cannot insert a column already added \n")

index1     0
index2    30
index3    60
index4    90
Name: column1, dtype: int64
        column1  new_column  column2  column3
index1        0           0        1        2
index2        3          30        4        5
index3        6          60        7        8
index4        9          90       10       11

 cannot insert a column already added 



**Handling duplicates**: Pandas `drop_duplicates()` method helps in removing duplicates from the DataFrame. `drop_duplicates()`  method returns DataFrame with duplicate rows removed.

In [14]:
# Let's see our DataFrame before removing duplicate rows
print(df_result)

   column1  column2  column3
0        0        1        2
1        3        4        5
2        6        7        8
3        9       10       11
4        0        1        2
5        3        4        5


In [15]:
# Remove duplicates calling drop_duplicates() with default behaviour:
df_without_duplicates = df_result.drop_duplicates()
print(df_without_duplicates)

   column1  column2  column3
0        0        1        2
1        3        4        5
2        6        7        8
3        9       10       11


As we can see, just like `append()`, the `drop_duplicates()` method will also return a copy of your DataFrame, but this time with duplicates removed. Using `inplace=True` will modify the DataFrame object in place. Let's check this point.

In [16]:
# Make a full copy of the df_result DataFame
df_full_copy = df_result.copy()
print(df_full_copy)

   column1  column2  column3
0        0        1        2
1        3        4        5
2        6        7        8
3        9       10       11
4        0        1        2
5        3        4        5


In [17]:
# Remove duplicates using inplace=True:
df_full_copy.drop_duplicates(inplace=True)
print(df_full_copy)

   column1  column2  column3
0        0        1        2
1        3        4        5
2        6        7        8
3        9       10       11


Another important argument for `drop_duplicates()` is `keep`, which has three possible options:

- `first`: (default) Drop duplicates except for the first occurrence.
- `last`: Drop duplicates except for the last occurrence.
- `False`: Drop all duplicates.

Let's see `last` and `False` options for argument `keep` in `drop_duplicats()` method (`first` is the default behaviour of this method and was seen in the previous example).

In [18]:
# Make a full copy of the df_result DataFame
df_full_copy = df_result.copy()
print(df_full_copy)

   column1  column2  column3
0        0        1        2
1        3        4        5
2        6        7        8
3        9       10       11
4        0        1        2
5        3        4        5


In [19]:
# Remove duplicates using using inplace=True and keep='last'
df_full_copy.drop_duplicates(inplace=True, keep='last')
print(df_full_copy)

   column1  column2  column3
2        6        7        8
3        9       10       11
4        0        1        2
5        3        4        5


In [20]:
# Make a full copy of the df_result DataFame
df_full_copy = df_result.copy()
print(df_full_copy)

   column1  column2  column3
0        0        1        2
1        3        4        5
2        6        7        8
3        9       10       11
4        0        1        2
5        3        4        5


In [21]:
# Remove duplicates using using inplace=True and keep=False
df_full_copy.drop_duplicates(inplace=True, keep=False)
print(df_full_copy)

   column1  column2  column3
2        6        7        8
3        9       10       11


**How to work with missing values**: When exploring data, you’ll most likely encounter missing or null values. Most commonly you'll see Python's None or NumPy's `np.nan`. There are two options in dealing with nulls:
- Get rid of rows or columns with nulls
- Replace nulls with non-null values, a technique known as imputation

So let's create a DataFrame.

In [22]:
# Make a full copy of the df_result DataFame
df_full_copy = df_result.copy()
print(df_full_copy)

   column1  column2  column3
0        0        1        2
1        3        4        5
2        6        7        8
3        9       10       11
4        0        1        2
5        3        4        5


 We are going to create some missing (or null) values using either:
 - numpy's `np.nan`
 - Python `None`

In [23]:
import numpy as np

# Create a list with some values (including some null values):
my_list = [100, None, np.nan]

# Create a Serie from the previous list:
my_serie = pd.Series(my_list, index = df_full_copy.columns)
print("This Serie (with NaN values) will be added: \n{}".format(my_serie))
# This commented line will also work
# my_serie = pd.Series(my_list, index = ['column1','column2', 'column3'])

# Append the created row to the dataFrame:
df_full_copy = df_full_copy.append(my_serie, ignore_index=True)

print(df_full_copy)

This Serie (with NaN values) will be added: 
column1    100.0
column2      NaN
column3      NaN
dtype: float64
   column1  column2  column3
0      0.0      1.0      2.0
1      3.0      4.0      5.0
2      6.0      7.0      8.0
3      9.0     10.0     11.0
4      0.0      1.0      2.0
5      3.0      4.0      5.0
6    100.0      NaN      NaN


Following previous approximation, we add several more rows with null values:

In [26]:
# Create some lists with some NaN values:
my_lists = [[100, np.nan, None], 
            [np.nan, np.nan, None],
            [np.nan, 200, np.nan]]

# Append these lists to the dataFrame:
for my_list in my_lists:
  my_serie = pd.Series(my_list, index = df_full_copy.columns)
  df_full_copy = df_full_copy.append(my_serie, ignore_index=True)

print(df_full_copy)

   column1  column2  column3
0      0.0      1.0      2.0
1      3.0      4.0      5.0
2      6.0      7.0      8.0
3      9.0     10.0     11.0
4      0.0      1.0      2.0
5      3.0      4.0      5.0
6    100.0      NaN      NaN
7    100.0      NaN      NaN
8      NaN      NaN      NaN
9      NaN    200.0      NaN


To check what values in the DataFrame are null we can use `isnull()` method:

In [44]:
df_full_copy.isnull()

column1  column2  column3
0    False    False    False
1    False    False    False
2    False    False    False
3    False    False    False
4    False    False    False
5    False    False    False
6    False     True     True
7    False     True     True
8     True     True     True
9     True    False     True

We usually want to know how many null values are in each column. Therefore we can count how many null values are for each column. 

In [45]:
df_full_copy.isnull().sum(axis=0)

column1    2
column2    3
column3    4
dtype: int64

From the previous output, we can see that in all columns there are null values. `column3` is the column with more null values (`4`).

To remember if you need to apply `axis=0` or `axis=1` as argument to an specific function: 

- `axis=0` to apply a method down each column
- `axis=1` to apply a method across each row

<img src="https://raw.githubusercontent.com/albertofernandezvillan/computer-vision-and-deep-learning-course/main/assets/numpy_and_pandas_axes.jpg">

Previous figure can be seen [here](https://stackoverflow.com/questions/17079279/how-is-axis-indexed-in-numpys-array) or [here](https://stackoverflow.com/questions/25773245/ambiguity-in-pandas-dataframe-numpy-array-axis-definition).

If we want to calculate how many null values are in each row:

In [46]:
df_full_copy.isnull().sum(axis=1)

0    0
1    0
2    0
3    0
4    0
5    0
6    2
7    2
8    3
9    2
dtype: int64

From the previous output we can see that only the last rows have null values. At this point, once identified that we have both null values in some rows and all columns, we can: 
- Get rid of rows or columns with nulls
- Replace nulls with non-null values, a technique known as imputation

As a rule of thumb, removing null data is only suggested if you have a small amount of missing data, which can  be performed using `dropna()`. In this case, we are going to perform `dropna(axis=0)`, which drops all rows with a single null value, returnig a new DataFrame (without altering the original one) unless you specify `inplace=True`. You can also drop columns with null values by setting `axis=1`. Let's check this point.

In [47]:
print("DataFrame with null values:")
print(df_full_copy)
print("Removing all rows with null values:")
df_without_nan = df_full_copy.dropna(axis=0)
print(df_without_nan)
print("Removing all columns with null values:")
# As it can be seen we obtain a Empty DataFrame
df_without_nan = df_full_copy.dropna(axis=1)
print(df_without_nan)

DataFrame with null values:
   column1  column2  column3
0      0.0      1.0      2.0
1      3.0      4.0      5.0
2      6.0      7.0      8.0
3      9.0     10.0     11.0
4      0.0      1.0      2.0
5      3.0      4.0      5.0
6    100.0      NaN      NaN
7    100.0      NaN      NaN
8      NaN      NaN      NaN
9      NaN    200.0      NaN
Removing all rows with null values:
   column1  column2  column3
0      0.0      1.0      2.0
1      3.0      4.0      5.0
2      6.0      7.0      8.0
3      9.0     10.0     11.0
4      0.0      1.0      2.0
5      3.0      4.0      5.0
Removing all columns with null values:
Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


Instead of removing rows/cols with null values, another option is to replace nulls with non-null values (imputation), like the mean or median for that specific column. As an example, we are going to replace all null values with a specific value (e.g. `123`).


In [48]:
print("DataFrame with null values:")
print(df_full_copy)

print("DataFrame with all null values replaced with '123.0' value:")
df_without_nan = df_full_copy.copy()
df_without_nan.fillna(123.0, inplace = True)
print(df_without_nan)

DataFrame with null values:
   column1  column2  column3
0      0.0      1.0      2.0
1      3.0      4.0      5.0
2      6.0      7.0      8.0
3      9.0     10.0     11.0
4      0.0      1.0      2.0
5      3.0      4.0      5.0
6    100.0      NaN      NaN
7    100.0      NaN      NaN
8      NaN      NaN      NaN
9      NaN    200.0      NaN
DataFrame with all null values replaced with '123.0' value:
   column1  column2  column3
0      0.0      1.0      2.0
1      3.0      4.0      5.0
2      6.0      7.0      8.0
3      9.0     10.0     11.0
4      0.0      1.0      2.0
5      3.0      4.0      5.0
6    100.0    123.0    123.0
7    100.0    123.0    123.0
8    123.0    123.0    123.0
9    123.0    200.0    123.0


We can also replace each null value with the mean value of each corresponding column.

In [55]:
print("DataFrame with null values:")
print(df_full_copy)

print("DataFrame with non null values replaced with the mean:")
df_without_nan = df_full_copy.copy()
mean_col_1 = df_without_nan['column1'].mean()
mean_col_2 = df_without_nan['column2'].mean()
mean_col_3 = df_without_nan['column3'].mean()

df_without_nan["column1"].fillna(mean_col_1, inplace = True)
df_without_nan["column2"].fillna(mean_col_2, inplace = True)
df_without_nan["column3"].fillna(mean_col_3, inplace = True)

print(df_without_nan)

DataFrame with null values:
   column1  column2  column3
0      0.0      1.0      2.0
1      3.0      4.0      5.0
2      6.0      7.0      8.0
3      9.0     10.0     11.0
4      0.0      1.0      2.0
5      3.0      4.0      5.0
6    100.0      NaN      NaN
7    100.0      NaN      NaN
8      NaN      NaN      NaN
9      NaN    200.0      NaN
DataFrame with non null values replaced with the mean:
   column1     column2  column3
0    0.000    1.000000      2.0
1    3.000    4.000000      5.0
2    6.000    7.000000      8.0
3    9.000   10.000000     11.0
4    0.000    1.000000      2.0
5    3.000    4.000000      5.0
6  100.000   32.428571      5.5
7  100.000   32.428571      5.5
8   27.625   32.428571      5.5
9   27.625  200.000000      5.5


Previous functionality can be performed in a more compact way as follows

In [52]:
print("DataFrame with null values")
df_without_nan = df_full_copy.copy()
print(df_without_nan)

# 1. Create a dictionary with 'column:value' pairs:
means = df_without_nan[df_without_nan.columns].mean()
columns = df_full_copy.columns

# Seen that the dictionary 'values' is commonly created as follows: 
# values = {}
# for A, B in zip(columns, means):
#     values[A] = B

values = dict(zip(columns, means))

print("\nDict to be used to fill the null values \n{}\n".format(values))

print("DataFrame with non null values replaced with the mean:")
# 2. Use this dictionary to fill the null values:
df_without_nan.fillna(value=values, inplace=True)
print(df_without_nan)

DataFrame with null values
   column1  column2  column3
0      0.0      1.0      2.0
1      3.0      4.0      5.0
2      6.0      7.0      8.0
3      9.0     10.0     11.0
4      0.0      1.0      2.0
5      3.0      4.0      5.0
6    100.0      NaN      NaN
7    100.0      NaN      NaN
8      NaN      NaN      NaN
9      NaN    200.0      NaN
{'column1': 27.625, 'column2': 32.42857142857143, 'column3': 5.5}

Dict to be used to fill the null values 
{'column1': 27.625, 'column2': 32.42857142857143, 'column3': 5.5}

DataFrame with non null values replaced with the mean:
   column1     column2  column3
0    0.000    1.000000      2.0
1    3.000    4.000000      5.0
2    6.000    7.000000      8.0
3    9.000   10.000000     11.0
4    0.000    1.000000      2.0
5    3.000    4.000000      5.0
6  100.000   32.428571      5.5
7  100.000   32.428571      5.5
8   27.625   32.428571      5.5
9   27.625  200.000000      5.5


# Selecting subsets of data in pandas DataFrame

In this section, we will see  how to use the `[]` operator and `.loc` or `.iloc` indexers.

We already commented that each row and each column have:
- a specific 'label' that can be used to reference them
- a specific 'integer' that can be used to reference them (integer location)






## Indexing operator `[]`

In [57]:
numpy_data = np.array([np.arange(3), np.arange(3,6), np.arange(6,9), np.arange(9,12)])                 

df = pd.DataFrame(data=numpy_data, 
                  index=["index1", "index2", "index3", "index4"],
                  columns=["column1", "column2", "column3"])
df

column1  column2  column3
index1        0        1        2
index2        3        4        5
index3        6        7        8
index4        9       10       11

It’s possible to select multiple columns with just the indexing operator `[]` by passing it a list of column names. Selecting multiple columns returns a DataFrame. You can actually select a single column as a DataFrame with a one-item list returning also a DataFrame. Selecting a single column returns a Series.

In [64]:
df[["column1","column2"]]

column1  column2
index1        0        1
index2        3        4
index3        6        7
index4        9       10

Therefore, see the obtained types for the different columns selection.

In [67]:
print(type(df[["column1","column2"]]))
print(type(df[["column1"]]))
print(type(df["column1"]))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>



The take away from the indexin operator `[]` is:

- Its primary purpose is to select columns by the column names
- Select a single column as a Series
- Select multiple columns as a DataFrame 
- You actually can select rows with it, but this will not be shown here as it is confusing and not used often.

## The `.loc` indexer

The `.loc` indexer is used to select data by label of the rows and columns. Main properties of `.loc` are:

- Only uses labels
- Can select rows and columns simultaneously
- Selection can be a single label, a list of labels or a slice of labels
- Put a comma between row and column selections

In [72]:
# Select all rows and a list with one column
df.loc[:, ["column1"]]

column1
index1        0
index2        3
index3        6
index4        9

In [75]:
# Select a slice of rows and all columns
# Note that slicing here includes the last element
df.loc["index1":"index3", :]

column1  column2  column3
index1        0        1        2
index2        3        4        5
index3        6        7        8

In [88]:
# Selecting a single element:
# This returns a scalar value:
print(df.loc["index2", "column1"])
# This returns a DataFrame:
print(df.loc[["index2"], ["column1"]])

3
        column1
index2        3


## The `.iloc` indexer
The `.iloc` indexer is very similar to `.loc` but only uses integer locations to make its selections. The word .`iloc` stands for integer location. 

Therefore, the `.iloc` indexer is used to select data by label of the rows and columns. Main properties of `.iloc` are:

- Only uses integers
- Can select rows and columns simultaneously
- Selection can be a single label, a list of integers or a slice of integers
- Put a comma between row and column selections

In [90]:
# Select all rows and a list with one column
df.iloc[:, [0]]

column1
index1        0
index2        3
index3        6
index4        9

In [91]:
# Select a slice of rows and all columns
# Note that slicing here includes the last element
df.iloc[0:3, :]

column1  column2  column3
index1        0        1        2
index2        3        4        5
index3        6        7        8

In [93]:
# Selecting a single element:
# This returns a scalar value:
print(df.iloc[1, 0])
# This returns a DataFrame:
print(df.iloc[[1], [0]])

3
        column1
index2        3


# Conclusion

In this notebook an introduction to pandas is given. Remember to check [this tutorial about pandas](https://medium.com/dunder-data/selecting-subsets-of-data-in-pandas-6fcd0170be9c).