<a href="https://colab.research.google.com/github/albertofernandezvillan/dl-ml-notebooks/blob/main/NumpyIndexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**First of all, a small trick to print with colors (it will be necessary to show the results of this notebook)**




We should: 1) define the colors, 2) create the function to be called, 3) test it

In [39]:
# Small trick to print with colors
# For more info see: "https://www.geeksforgeeks.org/print-colors-python-terminal/"
# 1) Define the colors
class fg:
  black='\033[30m'
  red='\033[31m'
  green='\033[32m'
  orange='\033[33m'
  blue='\033[34m'
  purple='\033[35m'
  cyan='\033[36m'
  lightgrey='\033[37m'
  darkgrey='\033[90m'
  lightred='\033[91m'
  lightgreen='\033[92m'
  yellow='\033[93m'
  lightblue='\033[94m'
  pink='\033[95m'
  lightcyan='\033[96m'

# 2) Create the function to be called:
def printTextWithColor(color, text): print(color + "{}".format(text))

# 3) Test it:
printTextWithColor(fg.green, "HELLO")
printTextWithColor(fg.lightblue, "GOODBYE")

HELLO
GOODBYE


We can also use the python library "termcolor", but the orange color is not defined and we need this color to be shown in our example.
If you want to use 'termocolor' here it is how you can use it:

```
!pip install termcolor
from termcolor import colored

print(colored("This is going to be shown in magenta!!!!", 'magenta'))
```

**At this point, we can start with our task (Numpy Indexing)**

In [32]:
# Ref here for more information: https://www.geeksforgeeks.org/numpy-indexing/
# Import required packages:
import numpy as np

In [33]:
# Create a (6x6) array:
a = np.array([[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11], [12, 13, 14, 15, 16, 17], [18, 19, 20, 21, 22, 23], [24, 25, 26, 27, 28, 29], [30, 31, 32, 33, 34, 35]])
print(a.shape)

(6, 6)


**Let's see some types of indexing.
The next Figure summarizes what we are going to do**



For inserting the Figure, the following code is necessary:
```
<img src="https://raw.githubusercontent.com/albertofernandezvillan/dl-ml-notebooks/main/numpy-indexing.jpg">
```

<img src="https://raw.githubusercontent.com/albertofernandezvillan/dl-ml-notebooks/main/numpy-indexing.jpg">

In [44]:
# slicing and indexing
result_1 = a[0, 3:5]
result_2 = a[4:, 4:]
result_3 = a[:, 2]
result_4 = a[2::2, ::2]

printTextWithColor(fg.black, "\n a[0, 3:5]  = ")
printTextWithColor(fg.orange, result_1)

printTextWithColor(fg.black, "\n a[4:, 4:]  = ")
printTextWithColor(fg.lightblue, result_2)

printTextWithColor(fg.black, "\n a[:, 2]  = ")
printTextWithColor(fg.lightred, result_3)

printTextWithColor(fg.black, "\n a[2::2, ::2]  = ")
printTextWithColor(fg.lightgreen, result_4)



 a[0, 3:5]  = 
[3 4]

 a[4:, 4:]  = 
[[28 29]
 [34 35]]

 a[:, 2]  = 
[ 2  8 14 20 26 32]

 a[2::2, ::2]  = 
[[12 14 16]
 [24 26 28]]
